### ISSUE TITLE
It seems that no directory named lifelike

### ISSUE THREAD

**Issue by swstbecrpgmail** [Tencent-RoboticsX/lifelike-agility-and-play#1]
It seems that no directory named lifelike when setting up the environment.
<img width="588" alt="1720869423069" src="https://github.com/user-attachments/assets/ba9f9b95-7a88-4bdb-a344-e126d871e260">

**Comment by slivermoda** [comment]
> It seems that no directory named lifelike when setting up the environment. <img alt="1720869423069" width="588" src="https://private-user-images.githubusercontent.com/153968462/348468017-ba9f9b95-7a88-4bdb-a344-e126d871e260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTYyOTUsIm5iZiI6MTcyMTAxNTk5NSwicGF0aCI6Ii8xNTM5Njg0NjIvMzQ4NDY4MDE3LWJhOWY5Yjk1LTdhODgtNGJkYi1hMzQ0LWUxMjZkODcxZTI2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMzU5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzhkZGQzMzQyZGE0NTk1NWNkZDQ0ZTI5OTExNzE4MTRhNGYwMjViZGJlYjg5M2Q4ZDhjMTU5OWE0MTRiNDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VL2c9crPO2O2KiL-23-eXsbo7U_oq_Iu4alxVlqUFfo">

We missed the setup.py file last time. Thanks for reporting this issue. Now it is fixed. Please cd into the 'lifelike-agility-and-play' folder and install the repo.

**Comment by swstbecrpgmail** [comment]
> > It seems that no directory named lifelike when setting up the environment. <img alt="1720869423069" width="588" src="https://private-user-images.githubusercontent.com/153968462/348468017-ba9f9b95-7a88-4bdb-a344-e126d871e260.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTYyOTUsIm5iZiI6MTcyMTAxNTk5NSwicGF0aCI6Ii8xNTM5Njg0NjIvMzQ4NDY4MDE3LWJhOWY5Yjk1LTdhODgtNGJkYi1hMzQ0LWUxMjZkODcxZTI2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMzU5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzhkZGQzMzQyZGE0NTk1NWNkZDQ0ZTI5OTExNzE4MTRhNGYwMjViZGJlYjg5M2Q4ZDhjMTU5OWE0MTRiNDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VL2c9crPO2O2KiL-23-eXsbo7U_oq_Iu4alxVlqUFfo">
> 
> We missed the setup.py file last time. Thanks for reporting this issue. Now it is fixed. Please cd into the 'lifelike-agility-and-play' folder and install the repo.

Thank you very much for your early reply!
