### ISSUE TITLE
 How to convert raw_mocap_data into mocap_data？

### ISSUE THREAD

**Issue by Ming-Di** [Tencent-RoboticsX/lifelike-agility-and-play#2]
thx

**Comment by ZQX323** [comment]
Retargeting the raw mocap data to a robot varies depending on the specific robot, so we haven't provided a single script for this process. However, I can offer some guidance on how to perform retargeting:

1. Use a Python script to open the FBX file and extract 3-4 points from the dog's back to determine the base position and orientation of the robot dog.

2. Once you have determined the robot dog's base pose, select a point on each foot to serve as the end effector. Use inverse kinematics to calculate the joint angles for each leg of the robot dog.

A few things to keep in mind: our raw data was collected from a Labrador, so the height and leg spacing will differ from your robot dog. You will need to adjust the scale of the data according to the specific robot dog you are using.

**Comment by Ming-Di** [comment]
Thank you very much for your reply, it solved my problem.

**Comment by XinLang2019** [comment]
> Thank you very much for your reply, it solved my problem.

hello，are your question solving? Can you give me some details to do that?

**Comment by CAI23sbP** [comment]
@Ming-Di @ZQX323  How to get FBX file?
There is only exist .bvh file in this repository
