### ISSUE TITLE
Could you please provide a script for training with multiple GPUs?

### ISSUE THREAD

**Issue by Ming-Di** [Tencent-RoboticsX/lifelike-agility-and-play#3]
I tried modifying 
`python -i -m lifelike.bin.run_pg_learner --learner_spec=0:30003:30004,1:30005:30006`
, but it didn't work, and the model is not running on the GPU.

**Comment by Ming-Di** [comment]
Even when I use the default training script, the model doesn't run on the GPU. (I have already tested my environment on the TLeague project)

**Comment by ZQX323** [comment]
To start a training session, you need to open four terminals to run model_pool, league_mgr, learner, and actor. It's recommended to use the provided shell script to start them instead of launching each manually. Note that TLeague is designed to train models using distributed CPUs. If you don't have access to distributed CPUs, you might consider using an open-source reinforcement learning framework, such as Stable-Baselines.

**Comment by Ming-Di** [comment]
> To start a training session, you need to open four terminals to run model_pool, league_mgr, learner, and actor. It's recommended to use the provided shell script to start them instead of launching each manually. Note that TLeague is designed to train models using distributed CPUs. If you don't have access to distributed CPUs, you might consider using an open-source reinforcement learning framework, such as Stable-Baselines.

I used the training script provided in the code, but it seems that the model is running on the CPU, whereas the paper mentions that training PMC used 2*V100 GPUs.

**Comment by ZQX323** [comment]
You can check the the visible_device_list here. https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/pg_learner.py#L81

**Comment by Ming-Di** [comment]
> You can check the the visible_device_list here. https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/pg_learner.py#L81
![1](https://github.com/user-attachments/assets/b91c19fc-6a8b-484c-bf8a-c56aa269dda2)
It looks fine...

**Comment by ZQX323** [comment]
The principle here is straightforward. The code sets one GPU as visible [here](https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/pg_learner.py#L81), and then the graph is built on that device [in this line](https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/pg_learner.py#L143). You might want to check if your environment is properly configured for this. You can try running some simple TensorFlow scripts to ensure that the model is using the GPU correctly.

**Comment by Ming-Di** [comment]
I have tried your method, but the graphics memory usage was always under 1000 MB. Is this excepted?

**Comment by Ming-Di** [comment]
> The principle here is straightforward. The code sets one GPU as visible [here](https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/pg_learner.py#L81), and then the graph is built on that device [in this line](https://github.com/tencent-ailab/TLeague/blob/dev-open/tleague/learners/pg_learner.py#L143). You might want to check if your environment is properly configured for this. You can try running some simple TensorFlow scripts to ensure that the model is using the GPU correctly.

I have tried your method, but the graphics memory usage was always under 1000 MB. Is this expected?
(batch size = 8192)

**Comment by ZQX323** [comment]
Yes, beacuse the size of policy is small

**Comment by Ming-Di** [comment]
Ok. Thanks for your reply~
