### ISSUE TITLE
cannot meet the protobuf version when compile the lifelike package 

### ISSUE THREAD

**Issue by WANGJIONG612** [Tencent-RoboticsX/lifelike-agility-and-play#4]
![截图 2024-08-14 14-21-37](https://github.com/user-attachments/assets/9bfb1dff-24f5-4e8b-8887-3c94ff0fae8e)

**Comment by slivermoda** [comment]
You can try protobuf version lower than 3.20.0, such as 3.19, which worked well as we tested
