### ISSUE TITLE
Hello, may I ask how you mapped bvh files to max.urdf ？Did you use some scripts or software?

### ISSUE THREAD

**Issue by lyt719** [Tencent-RoboticsX/lifelike-agility-and-play#5]

**Comment by slivermoda** [comment]
Similar questions were in the closed issue. Please refer to answers at

https://github.com/Tencent-RoboticsX/lifelike-agility-and-play/issues/2

**Comment by slivermoda** [comment]
Similar questions were in closed issues. Please refer to https://github.com/Tencent-RoboticsX/lifelike-agility-and-play/issues/2

**Comment by lyt719** [comment]
> Similar questions were in closed issues. Please refer to #2类似的问题也出现在非公开问题中。请参考 #2
Thank you very much. But it seems like you didn't mention about the tool in issue 2. May i ask for the tool or software name? Or may I ask if you can provide a script code? Thanks!

**Comment by slivermoda** [comment]
> > Similar questions were in closed issues. Please refer to #2类似的问题也出现在非公开问题中。请参考 #2
> > Thank you very much. But it seems like you didn't mention about the tool in issue 2. May i ask for the tool or software name? Or may I ask if you can provide a script code? Thanks!

Sure, we used CCD-IK, and after that we manually edited the retargeted reference to better fit the MAX robot. You can follow this trick on your own robot.
