### ISSUE TITLE
it seems that I got onlt 1 actor with a terminal

### ISSUE THREAD

**Issue by Huisouan** [Tencent-RoboticsX/lifelike-agility-and-play#6]
When using TLeague, each terminal can open only one actor. Is there a way to run multiple actors simultaneously on one computer for training, similar to Isaac Gym?

**Comment by Huisouan** [comment]
![image](https://github.com/user-attachments/assets/1a8764cd-9b4c-40b0-ba22-26817403b94b)
by the way,if I adjust the batch_size in actor_policy_config,ill get this valueerror

**Comment by slivermoda** [comment]
> When using TLeague, each terminal can open only one actor. Is there a way to run multiple actors simultaneously on one computer for training, similar to Isaac Gym?

TLeague is a distributed RL infrastructure, and you can simply write a bash scripts to loop and launch multiple actors to fit your computing resources. Everything goes in a distributed way. Isaac Gym support GPU inference for environment dynamics, so training with Isaac does not need to use distributed learner-actor infra. But pybullet or other physics engine can not.
