### ISSUE TITLE
can you tell me your parameter detail in paper used?

### ISSUE THREAD

**Issue by XinLang2019** [Tencent-RoboticsX/lifelike-agility-and-play#9]
Hello, excuse me! I had run your code to train a pmc policy. But I don't know if this figure of training is right, so can you give me your training parameter (I heard this profile parameter is different from what your paper used)?
![2024-09-29 14-06-21 的屏幕截图](https://github.com/user-attachments/assets/ef07972e-e29d-4244-b8a6-d92f8b82b50d)
![2024-09-29 14-13-12 的屏幕截图](https://github.com/user-attachments/assets/eab1237e-a45e-4979-b310-dc6cc8d64b8c)
![2024-09-29 14-13-45 的屏幕截图](https://github.com/user-attachments/assets/881cfb87-b51f-4fd8-a73f-0affb8339e4a)

**Comment by slivermoda** [comment]
Please refer to 
https://github.com/Tencent-RoboticsX/lifelike-agility-and-play/issues/7#issuecomment-2381953585
